### ISSUE TITLE
hdx.get_validlocations() network call should not be part of Configuration.create

### ISSUE THREAD

**Issue by bdon** [OCHA-DAP/hdx-python-api#11]
It would be better if this external network call was an explicit method on the Configuration. Configuration objects should be able to be used in environments without network access. It is also easy to make the mistake of calling Configuration.create many times without realizing that each call results in a network request, resulting in hundreds or more superfluous requests to the CKAN API. 

This is somewhat related to https://github.com/OCHA-DAP/hdx-python-api/issues/7 - if it was explicit that Configuration.create is only called once, and the resulting object was passed around, repeated calls to get_validlocations would be less of an issue

**Comment by mcarans** [comment]
I have released a fix for this in version 1.2. There are a number of new methods in the Configuration. create() now checks if a configuration has been made before and raises an exception if it has. But you have access to a _create() that bypasses the check, as well as individual methods to set remoteckan, validlocations etc. if preferred.  Please confirm and close.

**Comment by bdon** [comment]
BTW, we ran into another issue regarding the Configuration being a module-level singleton; the CKAN api depends on the `requests` library, which does not seem to be fork-safe, leading to an intermittent SSL exception happening in a multi-process application (in this case the popular `celery` job queue library). If the Configuration could be instantiated multiple times and passed it would be much easier to work around this

**Comment by mcarans** [comment]
Would it help if each time there is a call to CKAN a new CKAN instance is created rather than just using a single CKAN object, the result being a new `requests.Session()` is made for each call to CKAN?

(ie. instead of there just being `ckanapi.RemoteCKAN(site, apikey, useragent)` created just once and returned by `Configuration.remoteckan()`, instead `Configuration.remoteckan()` would make a new `ckanapi.RemoteCKAN(site, apikey, useragent)` each time it is called.)

**Comment by mcarans** [comment]
This should be fixed in 1.2.1. Please confirm and close.

**Comment by mcarans** [comment]
@mojodna Are you able to look at this?

**Comment by bdon** [comment]
Going back on what I mentioned on the first post ^ Instead of calling CKAN on Configuration creation, what if asking for valid locations was lazy-loaded? that way loading a Configuration in test environments wouldn't call the network, unless you accessed the validlocations ... although that still isn't totally explicit

**Comment by mcarans** [comment]
Lazy loading is in 1.2.2. Please confirm and close.
